replicaCount: 2
image:
  repository: dizevbije/complete-devops-project
  tag: c0674a3
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
httpRoute:
  enabled: false
